[package]
name = "goxlr-profile-loader"
version = "0.10.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.4.2"
enum-map-derive = "0.11.0"
thiserror = "1.0.38"
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }
strum = { version = "0.24.1", features = ["derive"] }
ritelinked = "0.3.2"
quick-xml = "0.27.1"
byteorder = "1.4.3"
rand = "0.8.5"

anyhow = "1.0.68"
log = "0.4.17"
