[package]
name = "goxlr-initialiser"
version = "0.10.2"
edition = "2021"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>", "Craig McLure <craig@mclure.net>", "Lars Mühlbauer <lm41@dismail.de>"]
description = "Finds, checks and initialises any unconfigured GoXLR devices"
repository = "https://github.com/GoXLR-on-Linux/GoXLR-Utility"
license = "MIT"
categories = ["hardware-support", "command-line-utilities"]

[dependencies]
rusb = "0.9.1"
anyhow = "1.0.68"
cfg-if = "1.0.0"
