[package]
name = "goxlr-client"
version = "0.10.2"
edition = "2021"
build = "build.rs"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>", "Craig McLure <craig@mclure.net>", "Lars Mühlbauer <lm41@dismail.de>"]
description = "Allows control of a TC-Helicon GoXLR or GoXLR Mini, by interacting with a running daemon."
repository = "https://github.com/GoXLR-on-Linux/GoXLR-Utility"
license = "MIT"
categories = ["hardware-support", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxlr-ipc = {path = "../ipc"}
goxlr-types = { path = "../types", features = ["clap"] }
tokio = {version = "1.23.0", features=["full"]}
simplelog = "0.12.0"
anyhow = "1.0"
clap = { version = "4.0.32", features = ["derive"] }
strum = { version = "0.24.1"}
serde_json = { version = "1.0.91" }
tokio-serde = { version = "0.8.0", features=["json"]}
interprocess = { version = "1.2.1", features=["tokio_support"] }

[build-dependencies]
clap = { version = "4.0.32", features = ["derive"] }
clap_complete = "4.0.7"
goxlr-types = { path = "../types", features = ["clap"] }
